// Downloads the OpenMoji color SVGs for every emoji glyph used in the catalog UI and writes
// a glyph -> filename map. OpenMoji (https://openmoji.org) is licensed CC BY-SA 4.0 — see
// public/emoji/LICENSE.txt. Re-run with: `node scripts/fetch-emoji.mjs`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const VERSION = '15.0.0';
const BASE = `https://cdn.jsdelivr.net/npm/openmoji@${VERSION}/color/svg`;
const OUT_DIR = join(ROOT, 'public', 'emoji');

// Files whose emoji glyphs are rendered in the DOM (covers, cards, scores, achievements).
const SOURCES = ['src/core/Registry.ts', 'src/store/achievements.ts'];

const text = SOURCES.map((f) => readFileSync(join(ROOT, f), 'utf8')).join('\n');

// Pull out every emoji grapheme cluster (handles ZWJ sequences + variation selectors).
const seg = new Intl.Segmenter('en', { granularity: 'grapheme' });
const isPict = (c) => [...c].some((ch) => /\p{Extended_Pictographic}/u.test(ch));
const glyphs = new Set();
for (const { segment } of seg.segment(text)) if (isPict(segment)) glyphs.add(segment);

// OpenMoji filenames are the codepoints in uppercase hex joined by '-', dropping U+FE0F.
const fileFor = (g) =>
  [...g]
    .map((c) => c.codePointAt(0))
    .filter((cp) => cp !== 0xfe0f)
    .map((cp) => cp.toString(16).toUpperCase())
    .join('-') + '.svg';

mkdirSync(OUT_DIR, { recursive: true });

const map = {};
const misses = [];
for (const g of [...glyphs].sort()) {
  const file = fileFor(g);
  const res = await fetch(`${BASE}/${file}`);
  if (!res.ok) {
    misses.push(`${g} -> ${file} (${res.status})`);
    continue;
  }
  writeFileSync(join(OUT_DIR, file), await res.text());
  map[g] = file;
}

writeFileSync(
  join(OUT_DIR, 'LICENSE.txt'),
  `Emoji graphics in this folder are from OpenMoji (https://openmoji.org), version ${VERSION}.\n` +
    `Licensed under Creative Commons CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).\n`,
);

const entries = Object.entries(map)
  .map(([g, f]) => `  ${JSON.stringify(g)}: ${JSON.stringify(f)},`)
  .join('\n');
writeFileSync(
  join(ROOT, 'src', 'core', 'emojiMap.ts'),
  `// AUTO-GENERATED by scripts/fetch-emoji.mjs — do not edit by hand.\n` +
    `// OpenMoji ${VERSION} color SVGs (CC BY-SA 4.0). Run \`node scripts/fetch-emoji.mjs\` to refresh.\n` +
    `export const EMOJI_MAP: Readonly<Record<string, string>> = {\n${entries}\n};\n`,
);

console.log(`Fetched ${Object.keys(map).length} emoji into public/emoji/`);
if (misses.length) console.warn(`Missing (${misses.length}):\n  ${misses.join('\n  ')}`);
